server:
  servlet:
    context-path: /elastic

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_elasticsearch?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  elasticsearch:
    uris: http://localhost:9200

  data:
    elasticsearch:
      repositories:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: train_elasticsearch
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Debezium configuration      
debezium:
  enabled: true